// <auto-generated />
using EduPortal.Dal.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EduPortal.Dal.Migrations
{
    [DbContext(typeof(EduPortalContext))]
    [Migration("20250730144515_AddFullName")]
    partial class AddFullName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EduPortal.Dal.Models.Graduate", b =>
                {
                    b.Property<string>("IDNumber")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AddFatherBusinessPhone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AddHomePhone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Age")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Apartment")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Cycle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Entrance")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FatherApartment")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FatherBusinessPhone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FatherCity")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FatherEntrance")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FatherHouseNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FatherPhone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FatherStreet")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HomePhone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MobilePhone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Passport")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IDNumber");

                    b.ToTable("Graduate");
                });

            modelBuilder.Entity("EduPortal.Dal.Models.YeshivaStudent", b =>
                {
                    b.Property<string>("IdNumber")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EntryDate")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdNumber");

                    b.ToTable("YeshivaStudent");
                });
#pragma warning restore 612, 618
        }
    }
}
